/**
 * Standard API error response shape matching ARCHITECTURE.md Section 9.4.
 */
export interface ApiErrorResponse {
  readonly error: {
    readonly code: string;
    readonly message: string;
  };
}

export const API_ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  CONCURRENCY_CONFLICT: "CONCURRENCY_CONFLICT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_RESPONSE_SCHEMA: "INVALID_RESPONSE_SCHEMA",
  MALFORMED_JSON: "MALFORMED_JSON",
  UNKNOWN_FIELD: "UNKNOWN_FIELD",
  INVALID_VALUE_TYPE: "INVALID_VALUE_TYPE",
  INVALID_VALUE: "INVALID_VALUE",
  STATE_CONFLICT: "STATE_CONFLICT",
  TRANSITION_ERROR: "TRANSITION_ERROR",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  PERSISTENCE_ERROR: "PERSISTENCE_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
